# Generated by Django 3.1.6 on 2021-03-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='vote',
            field=models.FloatField(choices=[(-1, -1), (0, 0), (1, 1)], null=True),
        ),
    ]
