# Generated by Django 3.1.6 on 2021-03-10 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='post_id',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='post',
            new_name='post_id',
        ),
    ]
