# Generated by Django 3.1.6 on 2021-04-07 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20210405_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
