# Generated by Django 2.2.13 on 2021-04-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_comment_comment_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='about_me',
            field=models.CharField(default='About Me', max_length=10000, null=True),
        ),
    ]
