# Generated by Django 3.2 on 2021-04-24 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_account_about_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_picture',
            field=models.ImageField(default='img/moolah.png', null=True, upload_to='img'),
        ),
    ]
